// Code generated by mockery v2.44.1. DO NOT EDIT.

package repomocks

import (
	models "github.com/geshtng/go-base-backend/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type ArticleRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *ArticleRepository) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *ArticleRepository) GetAll() ([]*models.Article, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Article, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Article); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ArticleRepository) GetByID(id int64) (*models.Article, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*models.Article, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *models.Article); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: article
func (_m *ArticleRepository) Insert(article models.Article) (*models.Article, error) {
	ret := _m.Called(article)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Article) (*models.Article, error)); ok {
		return rf(article)
	}
	if rf, ok := ret.Get(0).(func(models.Article) *models.Article); ok {
		r0 = rf(article)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(models.Article) error); ok {
		r1 = rf(article)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, article
func (_m *ArticleRepository) Update(id int64, article models.Article) (*models.Article, error) {
	ret := _m.Called(id, article)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, models.Article) (*models.Article, error)); ok {
		return rf(id, article)
	}
	if rf, ok := ret.Get(0).(func(int64, models.Article) *models.Article); ok {
		r0 = rf(id, article)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, models.Article) error); ok {
		r1 = rf(id, article)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewArticleRepository creates a new instance of ArticleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleRepository {
	mock := &ArticleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
